### ISSUE TITLE
Figure out how to get people into the discord/attract people to the project

### ISSUE THREAD

**Issue by mmirman** [anarchy-ai/LLM-VM#201]
Put your ideas here!  We'll award our favorite idea $50 and swag to other ideas!

**Comment by us** [comment]
Here few ideas that come to my mind:

1. Dive into the Google Summer of Code Adventure!: Ever thought about taking our project on a thrilling journey as an official participant in Google Summer of Code? I've got the inside scoop as both a past student and mentor – count on me to help steer the ship.
2. It's a Marathon, Not a Sprint: Attracting folks isn't a quick sprint; it's a marathon. To make this race enjoyable, let's craft a game plan with sustainability in mind. Monthly meet-ups? Heck yeah! 🏃‍♀️🏃‍♂️
3. Manifesto Magic: Let's cook up a manifesto that's cooler than the other side of the pillow. It's like our project's mission statement, but with a splash of pizzazz.
4. Finding Our Rebel Alliance: On the quest for like-minded rebels, we'll wander the digital plains of places like Reddit, seeking supporters who march to the beat of their own drum.
5. Hackathons and Manifesto-Fueled Feats: How about throwing some hackathons and events that align perfectly with our manifesto? It's like a rally for the coolest cause around, and we're the hosts.
6. Stirring the Pot with Mission Blogs: We'll whip up some blog posts that spill the beans on our mission. Topics like why AI should be for everyone or the sci-fi-worthy perils of AI will surely grab the attention of some passionate communities!

So, grab your shades, because this project's future is looking bright and full of exciting adventures! 😎🚀

**Comment by mmirman** [comment]
@us Did you use chatgpt for that?

**Comment by VaishnaviMudaliar** [comment]
I feel the most important thing here is to spread awareness about the projects, which can be done by building creative posters and flashing them on social media platforms like LinkedIn, Instagram, Twitter because these are the places where people generally spend their time scrolling.
Another way that comes to my mind is by conducting hackathons! I am aware that this is already being done but if we keep doing this frequently, we would soon attract innovative minds to the project!
Thanks😊

**Comment by harshitkd** [comment]
I believe that posting about the project on LinkedIn and Twitter is one of the most important methods to draw people to it, as many individuals on these platforms are ready to contribute to initiatives like this, which will eventually help grow traffic on the discord server. This target audience participates in the online community, which immediately contributes to the project's promotion by sharing the blog or any other sort of infographic on various social media platforms.

**Comment by mmirman** [comment]
Y'all were the dataset for openai weren't u

**Comment by SainiAditya1** [comment]
Hey @mmirman , I am interested to do this.

**Comment by jessicarhodes893** [comment]
I believe that posting on LinkedIn is a good start, but I think it was said above. I believe marketing through social media apps that many of us scroll through on a day to day basis would be efficient in getting more people to the discord where we can tell them more about the project. I also believe that emphasizing the bounty system would attract more talented coders to the discord.

**Comment by bilal-aamer** [comment]
Got an amazing idea, ig it was discussed previously. 

Get involved with Open Source centric programs like MLH, GSoC, Outreachy, LFX, etc.

Since I believe this is one of the most OSS project out there. (IMO).
And its economical from the organization and really playout well in the dedication of the organization to be Open Source.

Bottom line is get this project on their platforms.

**Comment by us** [comment]
@mmirman hahaha 🤣 yes for better formatting, but ideas are mines :D here is my prompt:

```
can you write following that in a cool way, not too formal, friendly,

Here few ideas that comes to my mind:

1. join google summer of code as an organization! I have experience as a student and mentor I can help with that.
2. It's a long marathon there is no quick way to attract people, cuz of that we need some plan and sustainability, like monthly meetings
3. Having a good manifesto about the project!
4. Specify the community that can support us, like finding anarchic people in somewhere like Reddit etc.
5. Organizing some hackathons or events that fit the manifesto of that project.
6. Writing some blocks about our missions, like why AI should be democratized, what the danger of AI in the future etc, like anarchic topics that get the attention of specific communities!
```

**Comment by mmirman** [comment]
> Hey @mmirman , I am interested to do this.

Well [SainiAditya1](https://github.com/SainiAditya1) I did just create a referal award role in the discord :-)

**Comment by TeeChenxing** [comment]
Use the power of social media. One ways to get people interested long-term is to create a dedicated YouTube channel outlining project goals and the people behind it. You could make videos showing the progress of the project every week and add in the discord server during the video (just an example 🙂).

The advantages of this method goes further than just attracting people to the discord server. It could also serve to guide and share a sense of achievement with community members.

**Comment by nominbold** [comment]
I recommend playing a fun game that keeps the score of anyone who participates in the game. We could have it on a weekly basis, and whoever has the highest score at the end of the week gets a reward of some kind. The game could be related to AI or uses AI. I don't have a specific game I could recommend, but I could also help with the creation of games for Anarchy AI.

**Comment by Sulstice** [comment]
One thing that could be of use is pulling all the people hosting open source data:

https://github.com/Sulstice/Uptime-Cheminformatics
https://github.com/Sulstice/Uptime-Bacteria

You can also reach out to a lot of non-profits that host datasets for training AI. I have one for chemistry. It's good marketing/education and allows your own brand to grow.

**Comment by Ayushsahnios** [comment]
We can have some periodic streams on platforms like twitch or youtube where we can demonstrate the some applications and build up project ideas live which can pull up lot of interest.

**Comment by zachsueh2023** [comment]
Attracting Hackers to the Project:

1. **Participate in Various Online and Offline R&D Conferences**: Attend events like All Things Open, Open Source Series 101, and Codeland. These conferences attract a diverse audience, including individuals who may not be PhD-level experts. During presentations, share details about the project, its goals, challenges, and how individuals can contribute. This will provide hackers with a clear understanding of the project and how to join.
2. **Leverage Popular Developer Blogging Platforms**: Utilize widely-read developer blogging platforms like Aviyel, Dev.to, or Hashnode to publish articles and posts about your project. These platforms have large developer communities, making them ideal for reaching potential contributors.
3. **Utilize Social Media (Twitter) and Podcasts/Twitter Spaces**: Build your project's brand and reach out to hackers through social media channels like Twitter. Consider hosting or participating in podcasts and Twitter Spaces discussions related to your project, where you can engage with potential contributors and share project updates.
4. **Live Stream the Project Build Process on Twitch**: Use platforms like Twitch to live stream the development process of your project. This provides transparency and allows potential hackers to see how the project evolves in real-time, making it more appealing and accessible.

Attracting Hackers to Discord:

1. **Share Important Information on Discord Channels**: Ensure that your Discord server contains essential project information, such as documentation, FAQs, and guidelines for contributors. Make it a central hub for project-related resources.
2. **Use Discord for Internal Group Discussions**: Encourage team members and contributors to use Discord for internal discussions, collaboration, and decision-making. A well-organized Discord server can facilitate efficient communication within the project community.
3. **Host Interviews and Discussions on Discord**: Organize interviews, discussions, or Q&A sessions related to your project on Discord. This will attract individuals interested in the project and create opportunities for them to ask questions and get involved.
4. **Scheduled Discord Meetings**: Establish a regular schedule for Discord meetings. This can include weekly or bi-weekly meetings to discuss project progress, updates, and address any questions or concerns. Consistency in using Discord for meetings helps build a sense of community among project participants.
