### ISSUE TITLE
Setup issue for Ubuntu 20.04LTS

### ISSUE THREAD

**Issue by TrungBui59** [anarchy-ai/LLM-VM#276]
**Description**

I follow the guide at [README](https://github.com/anarchy-ai/LLM-VM/blob/main/README.md) and [SERVER_API](https://github.com/anarchy-ai/LLM-VM/blob/main/SERVER_API.md) but still having issues running the application

**Setup**
I tried it both way, one by create conda environment with python3.11 and one with Docker

- The issue with conda env:
This happen when I try to run llm_vm_server
```
File "/home/trungbui/.conda/envs/llm_vm/lib/python3.11/site-packages/beartype/_check/code/codemake.py", line 706, in make_check_expr
    die_if_hint_pep_unsupported(
  File "/home/trungbui/.conda/envs/llm_vm/lib/python3.11/site-packages/beartype/_util/hint/pep/utilpeptest.py", line 205, in die_if_hint_pep_unsupported
    raise BeartypeDecorHintPep484Exception(
beartype.roar.BeartypeDecorHintPep484Exception: Function torch.onnx.symbolic_helper._onnx_unsupported() return PEP 484 type hint "typing.NoReturn" invalid in this type hint context (i.e., "typing.NoReturn" valid only as non-nested return annotation).
(llm_vm) trungbui@trungbui-FX503VD:~/LLM-VM$
```

- The issue with Docker:
This happen when I tried to build the docker image from dockerfile
```
397.8     raise ReadTimeoutError(self._pool, None, "Read timed out.")
397.8 pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
398.1 
398.1 [notice] A new release of pip is available: 23.0.1 -> 23.2.1
398.1 [notice] To update, run: pip install --upgrade pip
------
Dockerfile:19
--------------------
  17 |     
  18 |     # Installs the Python dependencies from the current directory
  19 | >>> RUN pip3 install --no-cache-dir .
  20 |     
  21 |     # Run the script
--------------------
ERROR: failed to solve: process "/bin/sh -c pip3 install --no-cache-dir ." did not complete successfully: exit code: 2
```

**Comment by Phantom-Harsh** [comment]
It looks like you are encountering two different issues when trying to run the LLM-VM application, one when using a conda environment and another when using Docker. I'll provide solutions for both scenarios:

Issue with Conda Environment:
The error you're encountering in your conda environment is related to type hinting in Python 3.11 and a specific function in the `beartype` library. Here's how you can resolve this:

1. Check Python Version:
   First, ensure that you are using Python 3.11 in your conda environment by running:
   ```
   conda activate llm_vm
   python --version
   ```

&  Verify that the Python version is 3.11.

2. Update Dependencies:
   Update your conda environment's dependencies, especially the `beartype` library, which seems to be causing the issue:
   ```
   conda update beartype
   ```
3. Retry Running the Application:
   After updating the dependencies, try running the application again:
   ```
   llm_vm_server
   ```
Issue with Docker:
The issue with Docker seems to be related to a timeout while trying to fetch a package from the Python Package Index (PyPI). You can try the following steps to resolve it:
1. Check Internet Connection:
2. Increase Timeout:
   You can increase the timeout for pip by setting the `PIP_TIMEOUT` environment variable in your Dockerfile. Add the following line before the `RUN pip3 install --no-cache-dir .` line in your Dockerfile:
   ```Dockerfile
   ENV PIP_TIMEOUT=1200  # Set a timeout value in seconds (e.g., 1200 seconds)
   ```
   This will give pip more time to download packages without timing out.
3. Retry Building the Docker Image:
   After making the changes to your Dockerfile, rebuild the Docker image:
   ```
   docker build -t llm-vm-image .
   ```
   Then, try running a container from the updated image:
   ```
   docker run -it llm-vm-image
   ```
   This should hopefully resolve the timeout issue during the Docker image build process.
Please make sure to replace `llm-vm-image` with the actual name you want to give to your Docker image if it's different. If you continue to face issues, provide more details about your Docker setup, such as your Dockerfile, so that I can provide more specific guidance.
