### ISSUE TITLE
Self referencing

### ISSUE THREAD

**Issue by Neoathenian** [anarchy-ai/LLM-VM#94]
Hello, I downloaded the project (no installation) as I wanted to edit it for the bounties.

As soon as I tried to compile it gave me an error like this:
Code:  from llm_vm.utils.keys import *
Error:   No module named 'llm_vm'

If I had installed it there´s no doubt it would´ve worked. However, when doing imports from the same project I think the usual way to navigate through folders is using dots, like: 
from ...utils.tools import *

Is there another way to go about this?

**Comment by ajn2004** [comment]
I think @cartazio can better answer this, but I think the issue you're running into is because we're not using relative imports for this project. [From what we've seen](https://peps.python.org/pep-0008/#imports) absolute imports are recommended over relative unless the path length is prohibitive. 

If you're trying to avoid a static build from hiding your changes, you can use an editable flag to have your changes reflected without constantly reinstalling the build.
```bash
> pip install --editable .
```
should do the trick for you, if everything I've said is on point. Let me know how if this helps.

**Comment by cartazio** [comment]
Yes, as Andrew says, to run the code in developer mode do `pip install —editable .` for an inplace, this ensures that code works in the same way weather as a developer or user

**Comment by cartazio** [comment]
The reason for absolute paths is that it makes the code more robust under refactoring or changes in how it’s organized

**Comment by cartazio** [comment]
closed as resolved
